### ISSUE TITLE
Fast switch off hoock in production mode

### ISSUE THREAD

**Issue by PredokMiF** [geobde/useRerender#2]
The hook looks very convenient, but there is no quick on/off option for production mode.

API can be like this:
```JSX
// index.jsx
useRender.production = false

ReactDOM.createRoot(appRootEl).render(
    <App/>
)
```

Or we can always disable hook in production mode by env.PRODUCTION, like react proptypes.

**Comment by geobde** [comment]
The env solution sounds good to me!
